version: '3.4'
services:
  confluence:
    image: dotiendat1751998/confluence
    container_name: confluence-srv
    environment:
      - TZ=Asia/Shanghai
        - JVM_MINIMUM_MEMORY=1g
        - JVM_MAXIMUM_MEMORY=4g
        - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=4g'
    depends_on:
      - mysql
    ports:
      - "8090:8090"
    volumes:
      - home_data:/var/confluence
    restart: always
    networks:
      - network-bridge

  mysql:
    image: mysql:8
    container_name: mysql-confluence
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=confluence
      - MYSQL_ROOT_PASSWORD=Adm1n123*#
      - MYSQL_USER=confluence
      - MYSQL_PASSWORD=Adm1n123*
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin','--transaction-isolation=READ-COMMITTED', '--innodb_log_file_size=256M', '--max_allowed_packet=256M' ]
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge

volumes:
  home_data:
    external: false
  mysql_data:
    external: false
