apiVersion: v1
kind: ReplicationController
metadata:
  name: jira-srv-repli # Tên của ReplicationController
spec:
  replicas: 2 # Số lượng Pod muốn chạy tại một thời điểm.
  selector:
    app: jira-srv # Label sử dụng để tim các pods để quản lý.
  template: # Phần này định nghĩa podTemplate để ReplicationController tạo.
    metadata:
      name: jira-srv
      labels:
        app: jira-srv
    spec:
      containers:
        - name: jira-srv
          image: dotiendat1751998/jira
#        - env:
#          - name: TZ
#            value: "Asia/Ho_Chi_Minh"
#          - name: VM_MINIMUM_MEMORY
#            value: "1g"
#          - name: JVM_MAXIMUM_MEMORY
#              value: "4g"
#          - name: JVM_CODE_CACHE_ARGS
#            value: "-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=4g"
          ports:
            - containerPort: 8080
      restartPolicy: Always
#          depends_on:
#            - mysql
#          volumes:
#            - home_data:/var/jira
#            restart: always
#            networks:
#              - network-bridge
#      container:
#        - name: mysql-jira
#          environment:
#            - TZ=Asia/Ho_Chi_Minh
#            - MYSQL_DATABASE=jira
#            - MYSQL_ROOT_PASSWORD=Adm1n123*#
#            - MYSQL_USER=jira
#            - MYSQL_PASSWORD=Adm1n123*
#          command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin','--transaction-isolation=READ-COMMITTED', '--innodb_log_file_size=256M', '--max_allowed_packet=256M']
#          ports:
#            - containerPort: 3306
##          volumes:
##            - mysql_data:/var/lib/mysql
#          restart: always
#          networks:
#            - network-bridge
